version: "3.4"
services:
  antifakenews:
    tty: true
    image: "antifakenews"
    stdin_open: true
    build:
      context: .
      target: "development"
    volumes:
      - ".:/src"
    env_file: .env
